---
- name: install nginx for Ubuntu
  apt:
    name: nginx
    state: latest
    update_cache: yes
  register: apt_result
  until: apt_result is not failed
  retries: 30
  delay: 10
  
- name: TEMPLATE; install new default template
  ansible.builtin.template:
    src: "nginx-default.j2"
    dest: "/etc/nginx/sites-enabled/default"
  notify:
    - Restart nginx
